version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: podcast_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  voice_service:
    build:
      context: ./voice_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/podcast_db
      ELEVEN_API_KEY: ${ELEVEN_API_KEY}
      MEDIA_DIR: /data
    volumes:
      - ./data:/data
      - ./voice_service/src:/app/src
    depends_on:
      - postgres

  script_service:
    build:
      context: ./script_service
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/podcast_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      TTS_SERVICE_URL: http://tts_service:8000
    volumes:
      - ./script_service/src:/app/src
    depends_on:
      - postgres
      - tts_service

  tts_service:
    build:
      context: ./tts_service
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/podcast_db
      ELEVEN_API_KEY: ${ELEVEN_API_KEY}
      MEDIA_DIR: /data/podcast-audio
    volumes:
      - ./data/podcast-audio:/data/podcast-audio
      - ./tts_service/src:/app/src
    depends_on:
      - postgres

  avatar_service:
    build:
      context: ./avatar_service
    ports:
      - "8004:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/podcast_db
      HEDRA_API_KEY: ${HEDRA_API_KEY}
      MEDIA_AUDIO_DIR: /data/podcast-audio
      MEDIA_VIDEO_DIR: /data/podcast-video
    volumes:
      - ./data/podcast-audio:/data/podcast-audio
      - ./data/podcast-video:/data/podcast-video
      - ./data/speaker-images:/data/speaker-images
      - ./avatar_service/src:/app/src
    depends_on:
      - postgres

  stitch_service:
    build:
      context: ./stitch_service
    ports:
      - "8005:8000"
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/podcast_db
      MEDIA_VIDEO_DIR: /data/podcast-video
      MEDIA_FINAL_DIR: /data/podcast-final
    volumes:
      - ./data/podcast-video:/data/podcast-video
      - ./data/podcast-final:/data/podcast-final
      - ./stitch_service/src:/app/src
    depends_on:
      - postgres

  react_admin_ui:
    build:
      context: ./react_admin_ui
    ports:
      - "3000:3000"
    environment:
      REACT_APP_VOICE_SERVICE_URL: http://localhost:8001
      REACT_APP_SCRIPT_SERVICE_URL: http://localhost:8002
      REACT_APP_TTS_SERVICE_URL: http://localhost:8003
      REACT_APP_AVATAR_SERVICE_URL: http://localhost:8004
      REACT_APP_STITCH_SERVICE_URL: http://localhost:8005
    volumes:
      - ./react_admin_ui/src:/app/src
      - ./react_admin_ui/public:/app/public
    depends_on:
      - voice_service
      - script_service
      - tts_service
      - avatar_service
      - stitch_service

volumes:
  postgres_data:

